name: beat

ide:
  intellij: false

packages:
  - packages/**
  - examples/**
  - tests/**
  - tools/**

scripts:
  test:
    run: melos bs && cd packages/generators && flutter pub run build_runner build && flutter test
  test-only:
    run: cd packages/generators && flutter test

command:
  bootstrap:
    usePubspecOverrides: true
