name: beat

ide:
  intellij: false

packages:
  - packages/**
  - examples/**
  - tools/**

scripts:
  test:
    run: melos bs && cd packages/generators && dart run build_runner test
  test-only:
    run: cd packages/generators && dart run build_runner test

command:
  bootstrap:
    usePubspecOverrides: true
