name: generators
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dependencies:
  analyzer: ^4.0.0
  build: ^2.3.1
  build_config: ^1.1.0
  collection: ^1.16.0
  meta: ^1.8.0
  source_gen: ^1.2.6
  annotations: ">=0.0.0 <1.0.0"

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.0
  build_test: ^2.1.5
  lints: ^2.0.0
  matcher: ^0.12.12
  source_gen_test: ^1.0.4
  test: ^1.16.0
